### ISSUE TITLE
Misleading

### ISSUE THREAD

**Issue by zachnewburgh** [learn-co-curriculum/orm-find-or-create-by#4]
The following makes it seem as if we were searching for an instance of the Song class when the code searches through the database for an entry, instead.

> At the end of our #find_or_create_by method, we will return the song object that we either found or created.

Perhaps a more representative phrasing would be:

> At the end of our #find_or_create_by method, we will return the song object **whose database entry** we either found or created. **This method assumes that there isn't already a song object matching these attributes, but that there may already exist a database entry with the same name and album. It, therefore, instantiates a new instance of the Song class, while preventing a duplication of the database entry.**

**Comment by AnnJohn** [comment]
Thanks @zachnewburgh. We're updating our curriculum within the next two months so will get to this as soon as we can.

**Comment by AnnJohn** [comment]
hi @PeterBell, not a rush, but can you review this issue and suggestion when you get a chance? thanks!

**Comment by PeterBell** [comment]
Hey @AnnJohn right now I'm trying to double down only on curriculum issues that are fixes for bugs students are coming up against - fixing specs or descriptions which are plain wrong or causing "ask a question" traffic due to being misleading. This doesn't feel like a bad change, but it's a little more subjective, and also at the moment a little lower priority. As such I'm gonna jump off this and let you assign to either Chuck or Joe as makes most sense.

**Comment by pletcher** [comment]
Hi @zachnewburgh, your suggestion seems good to me. Please feel free to open a PR!
